language: python
python:
    - "2.7"

install:
  - pip install -r package/test_requirements.txt --extra-index-url https://pypi.python.org/simple
  - pip install -r test_requirements.txt --extra-index-url https://pypi.python.org/simple
  - pip install "cloudshell-shell-core>=2.2.0,<2.3.0" --extra-index-url https://testpypi.python.org/simple
  - pip install "cloudshell-automation-api>=7.2.0.0,<7.3.0.0" --extra-index-url https://testpypi.python.org/simple

script:
    - pushd package
    - python setup.py develop
    - popd
    - python runtests.py --with-coverage  --cover-package=package --exclude setup.py

after_success:
    - coveralls

notifications:
    email: false
#notifications:
# webhools: https://qualisystems.getbadges.io/api/app/webhook/{will be added later}
